### ISSUE TITLE
API

### ISSUE THREAD

**Issue by nilsojes** [markus-t/Greenhouse-climate-control-software#2]
Vet inte hur bevandrad du är i webbtermer men jag funderar på om det inte skulle vara en bra lösning att bygga backend som ett API. Dvs. du skickar bara data (JSON) fram och tillbaka mellan själva servicen och webbappen. 

Då skulle man med ganska enkla medel även kunna få till att värden i gränssnittet uppdateras i realtid :)

**Comment by markus-t** [comment]
Det var precis så jag hade tänkt mig att det skulle bli till slut. :)
